#!/usr/bin/env ruby
# frozen_string_literal: true

# CLI example:
# ./change-rails-project
# ./change-rails-project project-directory
# ./change-rails-project project-directory feature-name
# ./change-rails-project project-directory feature-1 feature-2 feature-3 ...

require_relative "src/change_project/cli"

Dir.glob("#{__dir__}/features/*/*.rb", sort: true).each { |f| require_relative(f) }

ChangeProject::CLI.new(ARGV.dup).call
