#!/usr/bin/env ruby
ADDED_OR_MODIFIED = /^\s*(A|AM|M)/.freeze

changed_files = `git status --porcelain`.split(/\n/)
changed_files.select! { |line| line =~ ADDED_OR_MODIFIED }
changed_files.map! { |line| line.split(' ')[1] }

steps = [
  -> { system("eclint check #{changed_files.join(' ')}") }
]

if changed_files.empty? || steps.all?(&:call)
  exit 0
else
  exit 1
end
