# syntax = docker/dockerfile:1

ARG BASE_IMAGE=ruby:<%= ruby_version %>

#==================
FROM $BASE_IMAGE AS base

ARG PACKAGES="build-essential cmake pkg-config"
<% if includes_yarn %>
ARG PACKAGES="${PACKAGES} curl nodejs npm"
<% end %>
<% if includes_bun %>
ARG PACKAGES="${PACKAGES} unzip"
<% end %>
<% if database_packages %>
ARG PACKAGES="${PACKAGES} <%= database_packages %>"
<% end %>
<% if includes_active_storage %>
ARG PACKAGES="${PACKAGES} libvips"
<% end %>

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y ${PACKAGES} && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Application directory: /rails
RUN mkdir -m 0755 /rails
WORKDIR /rails
RUN mkdir -p -m 0755 tmp/pids tmp/storage log storage

<% if includes_yarn %>
RUN --mount=type=cache,uid=1000,target=/rails \
    npm install -g corepack && \
    corepack enable
<% end %>
<% if includes_bun %>
ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
# TODO: Specify version - `bash -s -- "${BUN_VERSION}"`
curl -fsSL https://bun.sh/install | bash
<% end %>

RUN gem install bundler:<%= bundler_version %>

<% if includes_yarn %>
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
<% end %>
<% if includes_bun %>
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
<% end %>
<% end %>

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . /rails
COPY .bundle/config.development .bundle/config

EXPOSE 3000

CMD ["bin/rails", "server", "-p", "3000" ,"-b", "0.0.0.0"]
