export default [
  {
    rules: {
      "array-callback-return": "error",
      "block-scoped-var": "error",
      "complexity": "warn",
      "consistent-return": "error",
      "curly": ["error", "multi", "consistent"],
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "max-depth": ["error", 6],
      "no-alert": "error",
      "no-case-declarations": "off",
      "no-console": "warn",
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-empty-function": "error",
      "no-eval": "warn",
      "no-extend-native": "error",
      "no-extra-label": "error",
      "no-fallthrough": ["warn", {"commentPattern": "дальше"}],
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": "warn",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-new-func": "warn",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable-loop": "error",
      "no-unused-vars": ["warn", {"vars": "local", "args": "all", "argsIgnorePattern": "^_"}],
      "no-use-before-define": "error",
      "no-useless-call": "warn",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "prefer-const": "error",
      "prefer-rest-params": "warn",
      "yoda": "warn",
    }
  }
]
