export default [
  {
    rules: {
      "array-bracket-newline": ["error", {"multiline": true}],
      "array-bracket-spacing": ["error", "never"],
      "array-callback-return": "error",
      "array-element-newline": ["error", "consistent"],
      "arrow-parens": ["error", "as-needed"],
      "arrow-spacing": "error",
      "block-scoped-var": "error",
      "block-spacing": ["error", "always"],
      "comma-dangle": [
        "error",
        {
          "arrays": "always-multiline",
          "objects": "always-multiline",
          "imports": "never",
          "exports": "never",
          "functions": "never"
        }
      ],
      "comma-spacing": ["error", {"before": false, "after": true}],
      "complexity": "warn",
      "computed-property-spacing": "error",
      "consistent-return": "error",
      "curly": ["error", "multi", "consistent"],
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "eol-last": "error",
      "func-call-spacing": "error",
      "function-call-argument-newline": ["error", "consistent"],
      "indent": [
        "error",
        2,
        {"SwitchCase": 1, "VariableDeclarator": "first", "MemberExpression": 2}
      ],
      "jsx-quotes": ["error", "prefer-double"],
      "key-spacing": ["warn", {"align": {"on": "value"}, "multiLine": {"mode": "minimum"}}],
      "keyword-spacing": ["error", {"before": true, "after": true}],
      "linebreak-style": ["error", "unix"],
      "max-depth": ["error", 6],
      "max-len": "error",
      "max-statements-per-line": "error",
      "no-alert": "error",
      "no-case-declarations": "off",
      "no-console": "warn",
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-empty-function": "error",
      "no-eval": "warn",
      "no-extend-native": "error",
      "no-extra-label": "error",
      "no-fallthrough": ["warn", {"commentPattern": "дальше"}],
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": "warn",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-multiple-empty-lines": ["error", {"max": 1}],
      "no-new-func": "warn",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-tabs": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable-loop": "error",
      "no-unused-vars": ["warn", {"vars": "local", "args": "all", "argsIgnorePattern": "^_"}],
      "no-use-before-define": "error",
      "no-useless-call": "warn",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-whitespace-before-property": "error",
      "nonblock-statement-body-position": ["error", "below"],
      "object-curly-newline": ["error", {"consistent": true}],
      "object-curly-spacing": ["error", "never"],
      "padded-blocks": ["error", "never"],
      "prefer-const": "error",
      "prefer-rest-params": "warn",
      "quotes": ["error", "single"],
      "space-before-function-paren": ["error", "never"],
      "space-in-parens": ["error", "never"],
      "space-infix-ops": "error",
      "spaced-comment": ["error", "always", {"markers": ["="]}],
      "switch-colon-spacing": "error",
      "yoda": "warn",
    }
  }
]
